### ISSUE TITLE
don't understand this line 

### ISSUE THREAD

**Issue by liloup1789** [javaidnabi31/Multi-Label-Text-classification-Using-BERT#3]
hello, 
I don't get this line : 

x_test = test[125000:140000]
it gives me : x text  = Empty DataFrame
Columns: [000idbert22889, Hola saber si chaqueta repelente agua referencia, 0.0, 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 21.0, 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26, 0.0.27, 0.0.28, 0.0.29, 0.0.30, 0.0.31, 0.0.32, 0.0.33, 0.0.34, 0.0.35, 0.0.36, 0.0.37, 0.0.38, 0.0.39, 0.0.40, 0.0.41, 0.0.42, 0.0.43, 0.0.44, 0.0.45, 0.0.46, 0.0.47, 0.0.48, 0.0.49, 0.0.50, 0.0.51, 0.0.52, 0.0.53, 0.0.54, 0.0.55, 0.0.56, 0.0.57, 0.0.58, 0.0.59, 0.0.60, 0.0.61, 0.0.62, 0.0.63, 0.0.64, 0.0.65, 0.0.66, 0.0.67, 0.0.68, 0.0.69, 0.0.70, 0.0.71, 0.0.72, 0.0.73, 0.0.74, 0.0.75, 0.0.76, 0.0.77, 0.0.78, 0.0.79, 0.0.80, 0.0.81, 0.0.82, 0.0.83, 0.0.84, 0.0.85, 0.0.86, 0.0.87, 0.0.88, 0.0.89, 0.0.90, 0.0.91, 0.0.92, 0.0.93, 0.0.94, 0.0.95, 0.0.96, ...]
Index: [] 

when i print it 
and the error : Traceback (most recent call last):
  File "Bert.py", line 904, in <module>
    dff.columns = BERTtest.LABEL_COLUMNS
  File "/home/tf/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 5080, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/tf/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 638, in _set_axis
    self._data.set_axis(axis, labels)
  File "/home/tf/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 155, in set_axis
    'values have {new} elements'.format(old=old_len, new=new_len))
ValueError: Length mismatch: Expected axis has 0 elements, new values have 114 elements
Any idea ? 

thanks

**Comment by BreakBB** [comment]
You can fix the latter issue by changing `for (i, prediction) in enumerate(predictions):` in "create_output" to `for prediction in predictions:`. The index "i" isn't used.

And about the test splitting: I have no clue where @javaidnabi31 got those numbers, but I changed the splitting of the data like this:

`split_1 = int(0.8 * len(train))
split_2 = int(0.9 * len(train))

x_train = train[:split_1]
x_eval = train[split_1:split_2]
x_test = train[split_2:]`

This will split the dataset of "train" into 80% train, 10% eval and 10% test data.

**Comment by javaidnabi31** [comment]
Actually 10k i used just to tun a quicker run. Otherwise you can use x_train= train[:SIZE_TRAIN]

**Comment by javaidnabi31** [comment]
I ran it on Kaggle https://www.kaggle.com/javaidnabi/toxic-comment-classification-using-bert
