### ISSUE TITLE
logits and labels are of different shape

### ISSUE THREAD

**Issue by dhirajpatnaik16297** [javaidnabi31/Multi-Label-Text-classification-Using-BERT#5]
I am new to this and trying to classify a self made data set into 15 classes so getting this error:

Traceback (most recent call last):
  File "train.py", line 656, in <module>
    estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1188, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1146, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "train.py", line 263, in model_fn
    num_labels, use_one_hot_embeddings)
  File "train.py", line 223, in create_model
    per_example_loss = tf.nn.sigmoid_cross_entropy_with_logits(labels=labels, logits=logits)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_impl.py", line 168, in sigmoid_cross_entropy_with_logits
    (logits.get_shape(), labels.get_shape()))
ValueError: logits and labels must have the same shape ((32, 15) vs (32, 6))

Let me know how to make changes in the model.
Thanks

**Comment by dhirajpatnaik16297** [comment]
Solved it.

**Comment by bakarin** [comment]
@dhirajpatnaik16297  could you post how you solved it?

**Comment by dhirajpatnaik16297** [comment]
In this function of train.py  "file_based_input_fn_builder(input_file, seq_length, is_training,drop_remainder)" you need to change 
""label_ids": tf.FixedLenFeature([CLASS SIZE], tf.int64)" line in "name_to_features" dictionary.

You must add the custom class size in place of CLASS SIZE.

Hope it helps.
